
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hotel_SoftWare2
{

using System;
    using System.Collections.Generic;
    
public partial class ChiTietPhieuThue
{

    public string MaChiTietPhieuThue { get; set; }

    public Nullable<System.DateTime> NgayVao { get; set; }

    public Nullable<System.DateTime> NgayRa { get; set; }

    public Nullable<bool> HinhThucThue { get; set; }

    public Nullable<byte> SoLuongKhach { get; set; }

    public string MaPhong { get; set; }

    public string MaPhieuThuePhong { get; set; }



    public virtual PhieuThuePhong PhieuThuePhong { get; set; }

    public virtual Phong Phong { get; set; }

}

}
