

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hotel_SoftWare2
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class htEntities : DbContext
{
    public htEntities()
        : base("name=htEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<ChiTietPhieuThue> ChiTietPhieuThues { get; set; }

    public virtual DbSet<DichVu> DichVus { get; set; }

    public virtual DbSet<HoaDon> HoaDons { get; set; }

    public virtual DbSet<KhachHang> KhachHangs { get; set; }

    public virtual DbSet<LoaiDichVu> LoaiDichVus { get; set; }

    public virtual DbSet<LoaiPhong> LoaiPhongs { get; set; }

    public virtual DbSet<NhanVien> NhanViens { get; set; }

    public virtual DbSet<PhieuSuDungDichVu> PhieuSuDungDichVus { get; set; }

    public virtual DbSet<PhieuThuePhong> PhieuThuePhongs { get; set; }

    public virtual DbSet<Phong> Phongs { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }


    public virtual int addCus(string mAKH, string tENKH, string cMND, string dIACHI, string sDT)
    {

        var mAKHParameter = mAKH != null ?
            new ObjectParameter("MAKH", mAKH) :
            new ObjectParameter("MAKH", typeof(string));


        var tENKHParameter = tENKH != null ?
            new ObjectParameter("TENKH", tENKH) :
            new ObjectParameter("TENKH", typeof(string));


        var cMNDParameter = cMND != null ?
            new ObjectParameter("CMND", cMND) :
            new ObjectParameter("CMND", typeof(string));


        var dIACHIParameter = dIACHI != null ?
            new ObjectParameter("DIACHI", dIACHI) :
            new ObjectParameter("DIACHI", typeof(string));


        var sDTParameter = sDT != null ?
            new ObjectParameter("SDT", sDT) :
            new ObjectParameter("SDT", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addCus", mAKHParameter, tENKHParameter, cMNDParameter, dIACHIParameter, sDTParameter);
    }


    public virtual int delCus(string mAKH)
    {

        var mAKHParameter = mAKH != null ?
            new ObjectParameter("MAKH", mAKH) :
            new ObjectParameter("MAKH", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delCus", mAKHParameter);
    }


    public virtual ObjectResult<getAccount_Result> getAccount()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAccount_Result>("getAccount");
    }


    public virtual ObjectResult<getallCus_Result> getallCus()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getallCus_Result>("getallCus");
    }


    public virtual int updateCus(string mAKH, string tENKH, string cMND, string dIACHI, string sDT)
    {

        var mAKHParameter = mAKH != null ?
            new ObjectParameter("MAKH", mAKH) :
            new ObjectParameter("MAKH", typeof(string));


        var tENKHParameter = tENKH != null ?
            new ObjectParameter("TENKH", tENKH) :
            new ObjectParameter("TENKH", typeof(string));


        var cMNDParameter = cMND != null ?
            new ObjectParameter("CMND", cMND) :
            new ObjectParameter("CMND", typeof(string));


        var dIACHIParameter = dIACHI != null ?
            new ObjectParameter("DIACHI", dIACHI) :
            new ObjectParameter("DIACHI", typeof(string));


        var sDTParameter = sDT != null ?
            new ObjectParameter("SDT", sDT) :
            new ObjectParameter("SDT", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateCus", mAKHParameter, tENKHParameter, cMNDParameter, dIACHIParameter, sDTParameter);
    }


    public virtual ObjectResult<logIn_Result> logIn(string tentk, string matkhau)
    {

        var tentkParameter = tentk != null ?
            new ObjectParameter("tentk", tentk) :
            new ObjectParameter("tentk", typeof(string));


        var matkhauParameter = matkhau != null ?
            new ObjectParameter("matkhau", matkhau) :
            new ObjectParameter("matkhau", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<logIn_Result>("logIn", tentkParameter, matkhauParameter);
    }


    public virtual int delEmp(string mANV)
    {

        var mANVParameter = mANV != null ?
            new ObjectParameter("MANV", mANV) :
            new ObjectParameter("MANV", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delEmp", mANVParameter);
    }


    public virtual ObjectResult<getallEmp_Result> getallEmp()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getallEmp_Result>("getallEmp");
    }


    public virtual int updateAcc(string mANV, string tenTK, string matkhau, Nullable<bool> quyen)
    {

        var mANVParameter = mANV != null ?
            new ObjectParameter("MANV", mANV) :
            new ObjectParameter("MANV", typeof(string));


        var tenTKParameter = tenTK != null ?
            new ObjectParameter("tenTK", tenTK) :
            new ObjectParameter("tenTK", typeof(string));


        var matkhauParameter = matkhau != null ?
            new ObjectParameter("matkhau", matkhau) :
            new ObjectParameter("matkhau", typeof(string));


        var quyenParameter = quyen.HasValue ?
            new ObjectParameter("quyen", quyen) :
            new ObjectParameter("quyen", typeof(bool));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateAcc", mANVParameter, tenTKParameter, matkhauParameter, quyenParameter);
    }


    public virtual int updateEmp(string mANV, string hOTEN, Nullable<System.DateTime> nGAYSINH, string sDT)
    {

        var mANVParameter = mANV != null ?
            new ObjectParameter("MANV", mANV) :
            new ObjectParameter("MANV", typeof(string));


        var hOTENParameter = hOTEN != null ?
            new ObjectParameter("HOTEN", hOTEN) :
            new ObjectParameter("HOTEN", typeof(string));


        var nGAYSINHParameter = nGAYSINH.HasValue ?
            new ObjectParameter("NGAYSINH", nGAYSINH) :
            new ObjectParameter("NGAYSINH", typeof(System.DateTime));


        var sDTParameter = sDT != null ?
            new ObjectParameter("SDT", sDT) :
            new ObjectParameter("SDT", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateEmp", mANVParameter, hOTENParameter, nGAYSINHParameter, sDTParameter);
    }


    public virtual int addEmp(string mANV, string hOTEN, Nullable<System.DateTime> nGAYSINH, string sDT)
    {

        var mANVParameter = mANV != null ?
            new ObjectParameter("MANV", mANV) :
            new ObjectParameter("MANV", typeof(string));


        var hOTENParameter = hOTEN != null ?
            new ObjectParameter("HOTEN", hOTEN) :
            new ObjectParameter("HOTEN", typeof(string));


        var nGAYSINHParameter = nGAYSINH.HasValue ?
            new ObjectParameter("NGAYSINH", nGAYSINH) :
            new ObjectParameter("NGAYSINH", typeof(System.DateTime));


        var sDTParameter = sDT != null ?
            new ObjectParameter("SDT", sDT) :
            new ObjectParameter("SDT", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addEmp", mANVParameter, hOTENParameter, nGAYSINHParameter, sDTParameter);
    }


    public virtual ObjectResult<getAcc1_Result> getAcc1()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAcc1_Result>("getAcc1");
    }


    public virtual ObjectResult<string> getIdMPT()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getIdMPT");
    }


    public virtual ObjectResult<string> wellCome(string tenTk, string matKhau)
    {

        var tenTkParameter = tenTk != null ?
            new ObjectParameter("TenTk", tenTk) :
            new ObjectParameter("TenTk", typeof(string));


        var matKhauParameter = matKhau != null ?
            new ObjectParameter("MatKhau", matKhau) :
            new ObjectParameter("MatKhau", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("wellCome", tenTkParameter, matKhauParameter);
    }


    public virtual int changePass(string matkhauhientai, string idnv)
    {

        var matkhauhientaiParameter = matkhauhientai != null ?
            new ObjectParameter("matkhauhientai", matkhauhientai) :
            new ObjectParameter("matkhauhientai", typeof(string));


        var idnvParameter = idnv != null ?
            new ObjectParameter("idnv", idnv) :
            new ObjectParameter("idnv", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("changePass", matkhauhientaiParameter, idnvParameter);
    }


    public virtual ObjectResult<string> getIdNV(string tenTk, string matKhau)
    {

        var tenTkParameter = tenTk != null ?
            new ObjectParameter("TenTk", tenTk) :
            new ObjectParameter("TenTk", typeof(string));


        var matKhauParameter = matKhau != null ?
            new ObjectParameter("MatKhau", matKhau) :
            new ObjectParameter("MatKhau", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getIdNV", tenTkParameter, matKhauParameter);
    }


    public virtual ObjectResult<getCusFrPhieuThue_Result> getCusFrPhieuThue(string maphieuthue)
    {

        var maphieuthueParameter = maphieuthue != null ?
            new ObjectParameter("maphieuthue", maphieuthue) :
            new ObjectParameter("maphieuthue", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCusFrPhieuThue_Result>("getCusFrPhieuThue", maphieuthueParameter);
    }


    public virtual ObjectResult<tienphongDetail_Result> tienphongDetail(string mptp)
    {

        var mptpParameter = mptp != null ?
            new ObjectParameter("mptp", mptp) :
            new ObjectParameter("mptp", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tienphongDetail_Result>("tienphongDetail", mptpParameter);
    }


    public virtual ObjectResult<tienDvDetail_Result> tienDvDetail(string maptp)
    {

        var maptpParameter = maptp != null ?
            new ObjectParameter("maptp", maptp) :
            new ObjectParameter("maptp", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tienDvDetail_Result>("tienDvDetail", maptpParameter);
    }


    public virtual int creatBill(string maHD, Nullable<double> tienphong, Nullable<double> tiendv, Nullable<double> tongtien, Nullable<bool> hinhthuctt, Nullable<System.DateTime> ngaytt, string ghichu, string mptp)
    {

        var maHDParameter = maHD != null ?
            new ObjectParameter("maHD", maHD) :
            new ObjectParameter("maHD", typeof(string));


        var tienphongParameter = tienphong.HasValue ?
            new ObjectParameter("tienphong", tienphong) :
            new ObjectParameter("tienphong", typeof(double));


        var tiendvParameter = tiendv.HasValue ?
            new ObjectParameter("tiendv", tiendv) :
            new ObjectParameter("tiendv", typeof(double));


        var tongtienParameter = tongtien.HasValue ?
            new ObjectParameter("tongtien", tongtien) :
            new ObjectParameter("tongtien", typeof(double));


        var hinhthucttParameter = hinhthuctt.HasValue ?
            new ObjectParameter("hinhthuctt", hinhthuctt) :
            new ObjectParameter("hinhthuctt", typeof(bool));


        var ngayttParameter = ngaytt.HasValue ?
            new ObjectParameter("ngaytt", ngaytt) :
            new ObjectParameter("ngaytt", typeof(System.DateTime));


        var ghichuParameter = ghichu != null ?
            new ObjectParameter("ghichu", ghichu) :
            new ObjectParameter("ghichu", typeof(string));


        var mptpParameter = mptp != null ?
            new ObjectParameter("mptp", mptp) :
            new ObjectParameter("mptp", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("creatBill", maHDParameter, tienphongParameter, tiendvParameter, tongtienParameter, hinhthucttParameter, ngayttParameter, ghichuParameter, mptpParameter);
    }


    public virtual ObjectResult<string> getHTTT()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getHTTT");
    }


    public virtual int creatBill1(string maHD, Nullable<double> tienphong, Nullable<double> tiendv, Nullable<double> tongtien, Nullable<bool> hinhthuctt, Nullable<System.DateTime> ngaytt, string ghichu, string mptp)
    {

        var maHDParameter = maHD != null ?
            new ObjectParameter("maHD", maHD) :
            new ObjectParameter("maHD", typeof(string));


        var tienphongParameter = tienphong.HasValue ?
            new ObjectParameter("tienphong", tienphong) :
            new ObjectParameter("tienphong", typeof(double));


        var tiendvParameter = tiendv.HasValue ?
            new ObjectParameter("tiendv", tiendv) :
            new ObjectParameter("tiendv", typeof(double));


        var tongtienParameter = tongtien.HasValue ?
            new ObjectParameter("tongtien", tongtien) :
            new ObjectParameter("tongtien", typeof(double));


        var hinhthucttParameter = hinhthuctt.HasValue ?
            new ObjectParameter("hinhthuctt", hinhthuctt) :
            new ObjectParameter("hinhthuctt", typeof(bool));


        var ngayttParameter = ngaytt.HasValue ?
            new ObjectParameter("ngaytt", ngaytt) :
            new ObjectParameter("ngaytt", typeof(System.DateTime));


        var ghichuParameter = ghichu != null ?
            new ObjectParameter("ghichu", ghichu) :
            new ObjectParameter("ghichu", typeof(string));


        var mptpParameter = mptp != null ?
            new ObjectParameter("mptp", mptp) :
            new ObjectParameter("mptp", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("creatBill1", maHDParameter, tienphongParameter, tiendvParameter, tongtienParameter, hinhthucttParameter, ngayttParameter, ghichuParameter, mptpParameter);
    }


    public virtual ObjectResult<getDoanhThuTienDV_Result> getDoanhThuTienDV(Nullable<System.DateTime> ngayvaochon, Nullable<System.DateTime> ngayrachon)
    {

        var ngayvaochonParameter = ngayvaochon.HasValue ?
            new ObjectParameter("ngayvaochon", ngayvaochon) :
            new ObjectParameter("ngayvaochon", typeof(System.DateTime));


        var ngayrachonParameter = ngayrachon.HasValue ?
            new ObjectParameter("ngayrachon", ngayrachon) :
            new ObjectParameter("ngayrachon", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDoanhThuTienDV_Result>("getDoanhThuTienDV", ngayvaochonParameter, ngayrachonParameter);
    }


    public virtual ObjectResult<getDoanhThuTienPhong_Result> getDoanhThuTienPhong(Nullable<System.DateTime> ngayvaochon, Nullable<System.DateTime> ngayrachon)
    {

        var ngayvaochonParameter = ngayvaochon.HasValue ?
            new ObjectParameter("ngayvaochon", ngayvaochon) :
            new ObjectParameter("ngayvaochon", typeof(System.DateTime));


        var ngayrachonParameter = ngayrachon.HasValue ?
            new ObjectParameter("ngayrachon", ngayrachon) :
            new ObjectParameter("ngayrachon", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDoanhThuTienPhong_Result>("getDoanhThuTienPhong", ngayvaochonParameter, ngayrachonParameter);
    }


    public virtual ObjectResult<getFreeRoom_Result> getFreeRoom()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getFreeRoom_Result>("getFreeRoom");
    }


    public virtual ObjectResult<getPhieuThue_Result> getPhieuThue()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPhieuThue_Result>("getPhieuThue");
    }


    public virtual ObjectResult<getRoomRented_Result> getRoomRented(string mptp)
    {

        var mptpParameter = mptp != null ?
            new ObjectParameter("mptp", mptp) :
            new ObjectParameter("mptp", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRoomRented_Result>("getRoomRented", mptpParameter);
    }


    public virtual ObjectResult<getPhieuThue2_Result> getPhieuThue2()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPhieuThue2_Result>("getPhieuThue2");
    }


    public virtual ObjectResult<string> getIdEmpFrAcc(string tentk, string matkhau)
    {

        var tentkParameter = tentk != null ?
            new ObjectParameter("tentk", tentk) :
            new ObjectParameter("tentk", typeof(string));


        var matkhauParameter = matkhau != null ?
            new ObjectParameter("matkhau", matkhau) :
            new ObjectParameter("matkhau", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getIdEmpFrAcc", tentkParameter, matkhauParameter);
    }


    public virtual int addCTPT(string mactpt, Nullable<System.DateTime> ngayvao, Nullable<System.DateTime> ngayra, Nullable<bool> htt, Nullable<byte> slk, string maphong, string mptp)
    {

        var mactptParameter = mactpt != null ?
            new ObjectParameter("mactpt", mactpt) :
            new ObjectParameter("mactpt", typeof(string));


        var ngayvaoParameter = ngayvao.HasValue ?
            new ObjectParameter("ngayvao", ngayvao) :
            new ObjectParameter("ngayvao", typeof(System.DateTime));


        var ngayraParameter = ngayra.HasValue ?
            new ObjectParameter("ngayra", ngayra) :
            new ObjectParameter("ngayra", typeof(System.DateTime));


        var httParameter = htt.HasValue ?
            new ObjectParameter("htt", htt) :
            new ObjectParameter("htt", typeof(bool));


        var slkParameter = slk.HasValue ?
            new ObjectParameter("slk", slk) :
            new ObjectParameter("slk", typeof(byte));


        var maphongParameter = maphong != null ?
            new ObjectParameter("maphong", maphong) :
            new ObjectParameter("maphong", typeof(string));


        var mptpParameter = mptp != null ?
            new ObjectParameter("mptp", mptp) :
            new ObjectParameter("mptp", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addCTPT", mactptParameter, ngayvaoParameter, ngayraParameter, httParameter, slkParameter, maphongParameter, mptpParameter);
    }


    public virtual int addPhieuThuePhong(string mptp, string ghichu, string makh, string manv)
    {

        var mptpParameter = mptp != null ?
            new ObjectParameter("mptp", mptp) :
            new ObjectParameter("mptp", typeof(string));


        var ghichuParameter = ghichu != null ?
            new ObjectParameter("ghichu", ghichu) :
            new ObjectParameter("ghichu", typeof(string));


        var makhParameter = makh != null ?
            new ObjectParameter("makh", makh) :
            new ObjectParameter("makh", typeof(string));


        var manvParameter = manv != null ?
            new ObjectParameter("manv", manv) :
            new ObjectParameter("manv", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addPhieuThuePhong", mptpParameter, ghichuParameter, makhParameter, manvParameter);
    }


    public virtual ObjectResult<getAllCTPT_Result> getAllCTPT()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllCTPT_Result>("getAllCTPT");
    }


    public virtual ObjectResult<getCTPT_FrIdPT_Result> getCTPT_FrIdPT(string mpt)
    {

        var mptParameter = mpt != null ?
            new ObjectParameter("mpt", mpt) :
            new ObjectParameter("mpt", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCTPT_FrIdPT_Result>("getCTPT_FrIdPT", mptParameter);
    }


    public virtual int updateCTPT(string mactpt, Nullable<System.DateTime> ngayvao, Nullable<System.DateTime> ngayra, Nullable<bool> htt, Nullable<byte> slk, string maphong, string mptp)
    {

        var mactptParameter = mactpt != null ?
            new ObjectParameter("mactpt", mactpt) :
            new ObjectParameter("mactpt", typeof(string));


        var ngayvaoParameter = ngayvao.HasValue ?
            new ObjectParameter("ngayvao", ngayvao) :
            new ObjectParameter("ngayvao", typeof(System.DateTime));


        var ngayraParameter = ngayra.HasValue ?
            new ObjectParameter("ngayra", ngayra) :
            new ObjectParameter("ngayra", typeof(System.DateTime));


        var httParameter = htt.HasValue ?
            new ObjectParameter("htt", htt) :
            new ObjectParameter("htt", typeof(bool));


        var slkParameter = slk.HasValue ?
            new ObjectParameter("slk", slk) :
            new ObjectParameter("slk", typeof(byte));


        var maphongParameter = maphong != null ?
            new ObjectParameter("maphong", maphong) :
            new ObjectParameter("maphong", typeof(string));


        var mptpParameter = mptp != null ?
            new ObjectParameter("mptp", mptp) :
            new ObjectParameter("mptp", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateCTPT", mactptParameter, ngayvaoParameter, ngayraParameter, httParameter, slkParameter, maphongParameter, mptpParameter);
    }


    public virtual int changeStatusRoom(string maphong)
    {

        var maphongParameter = maphong != null ?
            new ObjectParameter("maphong", maphong) :
            new ObjectParameter("maphong", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("changeStatusRoom", maphongParameter);
    }


    public virtual ObjectResult<string> getRentedRoom(string mptp)
    {

        var mptpParameter = mptp != null ?
            new ObjectParameter("mptp", mptp) :
            new ObjectParameter("mptp", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getRentedRoom", mptpParameter);
    }


    public virtual ObjectResult<getListRentedRoom_Result> getListRentedRoom()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getListRentedRoom_Result>("getListRentedRoom");
    }


    public virtual ObjectResult<getRentedRoomSearch_Result> getRentedRoomSearch(string mptp)
    {

        var mptpParameter = mptp != null ?
            new ObjectParameter("mptp", mptp) :
            new ObjectParameter("mptp", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRentedRoomSearch_Result>("getRentedRoomSearch", mptpParameter);
    }


    public virtual ObjectResult<getlistBill_Result> getlistBill()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getlistBill_Result>("getlistBill");
    }


    public virtual ObjectResult<string> getIdPTFromSDT(string sdt)
    {

        var sdtParameter = sdt != null ?
            new ObjectParameter("sdt", sdt) :
            new ObjectParameter("sdt", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getIdPTFromSDT", sdtParameter);
    }


    public virtual ObjectResult<string> getIdPTFromMaPhong(string tenphong)
    {

        var tenphongParameter = tenphong != null ?
            new ObjectParameter("tenphong", tenphong) :
            new ObjectParameter("tenphong", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getIdPTFromMaPhong", tenphongParameter);
    }

}

}

