//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_SoftWare2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class htEntities : DbContext
    {
        public htEntities()
            : base("name=htEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietPhieuThue> ChiTietPhieuThues { get; set; }
        public virtual DbSet<DichVu> DichVus { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiDichVu> LoaiDichVus { get; set; }
        public virtual DbSet<LoaiPhong> LoaiPhongs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuSuDungDichVu> PhieuSuDungDichVus { get; set; }
        public virtual DbSet<PhieuThuePhong> PhieuThuePhongs { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int addCus(string mAKH, string tENKH, string cMND, string dIACHI, string sDT)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            var tENKHParameter = tENKH != null ?
                new ObjectParameter("TENKH", tENKH) :
                new ObjectParameter("TENKH", typeof(string));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addCus", mAKHParameter, tENKHParameter, cMNDParameter, dIACHIParameter, sDTParameter);
        }
    
        public virtual int delCus(string mAKH)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delCus", mAKHParameter);
        }
    
        public virtual ObjectResult<getAccount_Result> getAccount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAccount_Result>("getAccount");
        }
    
        public virtual ObjectResult<getallCus_Result> getallCus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getallCus_Result>("getallCus");
        }
    
        public virtual int updateCus(string mAKH, string tENKH, string cMND, string dIACHI, string sDT)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            var tENKHParameter = tENKH != null ?
                new ObjectParameter("TENKH", tENKH) :
                new ObjectParameter("TENKH", typeof(string));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateCus", mAKHParameter, tENKHParameter, cMNDParameter, dIACHIParameter, sDTParameter);
        }
    
        public virtual ObjectResult<logIn_Result> logIn(string tentk, string matkhau)
        {
            var tentkParameter = tentk != null ?
                new ObjectParameter("tentk", tentk) :
                new ObjectParameter("tentk", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<logIn_Result>("logIn", tentkParameter, matkhauParameter);
        }
    
        public virtual int delEmp(string mANV)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delEmp", mANVParameter);
        }
    
        public virtual ObjectResult<getallEmp_Result> getallEmp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getallEmp_Result>("getallEmp");
        }
    
        public virtual int updateAcc(string mANV, string tenTK, string matkhau, Nullable<bool> quyen)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var tenTKParameter = tenTK != null ?
                new ObjectParameter("tenTK", tenTK) :
                new ObjectParameter("tenTK", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var quyenParameter = quyen.HasValue ?
                new ObjectParameter("quyen", quyen) :
                new ObjectParameter("quyen", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateAcc", mANVParameter, tenTKParameter, matkhauParameter, quyenParameter);
        }
    
        public virtual int updateEmp(string mANV, string hOTEN, Nullable<System.DateTime> nGAYSINH, string sDT)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var hOTENParameter = hOTEN != null ?
                new ObjectParameter("HOTEN", hOTEN) :
                new ObjectParameter("HOTEN", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateEmp", mANVParameter, hOTENParameter, nGAYSINHParameter, sDTParameter);
        }
    
        public virtual int addEmp(string mANV, string hOTEN, Nullable<System.DateTime> nGAYSINH, string sDT)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var hOTENParameter = hOTEN != null ?
                new ObjectParameter("HOTEN", hOTEN) :
                new ObjectParameter("HOTEN", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addEmp", mANVParameter, hOTENParameter, nGAYSINHParameter, sDTParameter);
        }
    
        public virtual ObjectResult<getAcc1_Result> getAcc1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAcc1_Result>("getAcc1");
        }
    
        public virtual ObjectResult<string> getIdMPT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getIdMPT");
        }
    
        public virtual ObjectResult<string> wellCome(string tenTk, string matKhau)
        {
            var tenTkParameter = tenTk != null ?
                new ObjectParameter("TenTk", tenTk) :
                new ObjectParameter("TenTk", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("wellCome", tenTkParameter, matKhauParameter);
        }
    
        public virtual int changePass(string matkhauhientai, string idnv)
        {
            var matkhauhientaiParameter = matkhauhientai != null ?
                new ObjectParameter("matkhauhientai", matkhauhientai) :
                new ObjectParameter("matkhauhientai", typeof(string));
    
            var idnvParameter = idnv != null ?
                new ObjectParameter("idnv", idnv) :
                new ObjectParameter("idnv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("changePass", matkhauhientaiParameter, idnvParameter);
        }
    
        public virtual ObjectResult<string> getIdNV(string tenTk, string matKhau)
        {
            var tenTkParameter = tenTk != null ?
                new ObjectParameter("TenTk", tenTk) :
                new ObjectParameter("TenTk", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getIdNV", tenTkParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<getCusFrPhieuThue_Result> getCusFrPhieuThue(string maphieuthue)
        {
            var maphieuthueParameter = maphieuthue != null ?
                new ObjectParameter("maphieuthue", maphieuthue) :
                new ObjectParameter("maphieuthue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCusFrPhieuThue_Result>("getCusFrPhieuThue", maphieuthueParameter);
        }
    
        public virtual int addSer(string mADV, string tENDV, Nullable<double> dONGIA, string mALOAIDICHVU)
        {
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            var tENDVParameter = tENDV != null ?
                new ObjectParameter("TENDV", tENDV) :
                new ObjectParameter("TENDV", typeof(string));
    
            var dONGIAParameter = dONGIA.HasValue ?
                new ObjectParameter("DONGIA", dONGIA) :
                new ObjectParameter("DONGIA", typeof(double));
    
            var mALOAIDICHVUParameter = mALOAIDICHVU != null ?
                new ObjectParameter("MALOAIDICHVU", mALOAIDICHVU) :
                new ObjectParameter("MALOAIDICHVU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addSer", mADVParameter, tENDVParameter, dONGIAParameter, mALOAIDICHVUParameter);
        }
    
        public virtual int addTypeRoom(string mALOAIPHONG, string tENLOAIPHONG, Nullable<byte> sONGUOI, string gHICHU)
        {
            var mALOAIPHONGParameter = mALOAIPHONG != null ?
                new ObjectParameter("MALOAIPHONG", mALOAIPHONG) :
                new ObjectParameter("MALOAIPHONG", typeof(string));
    
            var tENLOAIPHONGParameter = tENLOAIPHONG != null ?
                new ObjectParameter("TENLOAIPHONG", tENLOAIPHONG) :
                new ObjectParameter("TENLOAIPHONG", typeof(string));
    
            var sONGUOIParameter = sONGUOI.HasValue ?
                new ObjectParameter("SONGUOI", sONGUOI) :
                new ObjectParameter("SONGUOI", typeof(byte));
    
            var gHICHUParameter = gHICHU != null ?
                new ObjectParameter("GHICHU", gHICHU) :
                new ObjectParameter("GHICHU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addTypeRoom", mALOAIPHONGParameter, tENLOAIPHONGParameter, sONGUOIParameter, gHICHUParameter);
        }
    
        public virtual int addTypeSer(string mALOAIDV, string tENLOAIDV)
        {
            var mALOAIDVParameter = mALOAIDV != null ?
                new ObjectParameter("MALOAIDV", mALOAIDV) :
                new ObjectParameter("MALOAIDV", typeof(string));
    
            var tENLOAIDVParameter = tENLOAIDV != null ?
                new ObjectParameter("TENLOAIDV", tENLOAIDV) :
                new ObjectParameter("TENLOAIDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addTypeSer", mALOAIDVParameter, tENLOAIDVParameter);
        }
    
        public virtual int delSer(string mADV)
        {
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delSer", mADVParameter);
        }
    
        public virtual int delTypeRoom(string mALOAIPHONG)
        {
            var mALOAIPHONGParameter = mALOAIPHONG != null ?
                new ObjectParameter("MALOAIPHONG", mALOAIPHONG) :
                new ObjectParameter("MALOAIPHONG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delTypeRoom", mALOAIPHONGParameter);
        }
    
        public virtual int delTypeSer(string mALOAIDV)
        {
            var mALOAIDVParameter = mALOAIDV != null ?
                new ObjectParameter("MALOAIDV", mALOAIDV) :
                new ObjectParameter("MALOAIDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delTypeSer", mALOAIDVParameter);
        }
    
        public virtual ObjectResult<DSDichVu_Result> DSDichVu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSDichVu_Result>("DSDichVu");
        }
    
        public virtual ObjectResult<DSKHTP_Result> DSKHTP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSKHTP_Result>("DSKHTP");
        }
    
        public virtual ObjectResult<DSLoaiDichVu_Result> DSLoaiDichVu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSLoaiDichVu_Result>("DSLoaiDichVu");
        }
    
        public virtual ObjectResult<DSLoaiPhong_Result> DSLoaiPhong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSLoaiPhong_Result>("DSLoaiPhong");
        }
    
        public virtual ObjectResult<DSNV_Result> DSNV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSNV_Result>("DSNV");
        }
    
        public virtual int HTTT(string hTTT)
        {
            var hTTTParameter = hTTT != null ?
                new ObjectParameter("HTTT", hTTT) :
                new ObjectParameter("HTTT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HTTT", hTTTParameter);
        }
    
        public virtual ObjectResult<TENNV_Result> TENNV(string tenNV)
        {
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TENNV_Result>("TENNV", tenNVParameter);
        }
    
        public virtual ObjectResult<TIMNV_Result> TIMNV(string tenKH)
        {
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TIMNV_Result>("TIMNV", tenKHParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> TKKH(string tenLoaiPhong)
        {
            var tenLoaiPhongParameter = tenLoaiPhong != null ?
                new ObjectParameter("TenLoaiPhong", tenLoaiPhong) :
                new ObjectParameter("TenLoaiPhong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TKKH", tenLoaiPhongParameter);
        }
    
        public virtual ObjectResult<TKKHTHEOPHONG_Result> TKKHTHEOPHONG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TKKHTHEOPHONG_Result>("TKKHTHEOPHONG");
        }
    
        public virtual ObjectResult<TKKHTHEOSOLANTHUE_Result> TKKHTHEOSOLANTHUE(Nullable<int> sOLANTHUE)
        {
            var sOLANTHUEParameter = sOLANTHUE.HasValue ?
                new ObjectParameter("SOLANTHUE", sOLANTHUE) :
                new ObjectParameter("SOLANTHUE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TKKHTHEOSOLANTHUE_Result>("TKKHTHEOSOLANTHUE", sOLANTHUEParameter);
        }
    
        public virtual ObjectResult<TKKHTHEOSOPHONGTHUE_Result> TKKHTHEOSOPHONGTHUE(Nullable<int> sOPHONGTHUE)
        {
            var sOPHONGTHUEParameter = sOPHONGTHUE.HasValue ?
                new ObjectParameter("SOPHONGTHUE", sOPHONGTHUE) :
                new ObjectParameter("SOPHONGTHUE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TKKHTHEOSOPHONGTHUE_Result>("TKKHTHEOSOPHONGTHUE", sOPHONGTHUEParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> TKKHTHEOTHANG(string tHANG)
        {
            var tHANGParameter = tHANG != null ?
                new ObjectParameter("THANG", tHANG) :
                new ObjectParameter("THANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TKKHTHEOTHANG", tHANGParameter);
        }
    
        public virtual ObjectResult<TTKH_Result> TTKH(string maKH)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TTKH_Result>("TTKH", maKHParameter);
        }
    
        public virtual ObjectResult<TTNV_Result> TTNV(string maNV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TTNV_Result>("TTNV", maNVParameter);
        }
    
        public virtual int updateSer(string mADV, string tENDV, Nullable<double> dONGIA, string mALOAIDICHVU)
        {
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            var tENDVParameter = tENDV != null ?
                new ObjectParameter("TENDV", tENDV) :
                new ObjectParameter("TENDV", typeof(string));
    
            var dONGIAParameter = dONGIA.HasValue ?
                new ObjectParameter("DONGIA", dONGIA) :
                new ObjectParameter("DONGIA", typeof(double));
    
            var mALOAIDICHVUParameter = mALOAIDICHVU != null ?
                new ObjectParameter("MALOAIDICHVU", mALOAIDICHVU) :
                new ObjectParameter("MALOAIDICHVU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateSer", mADVParameter, tENDVParameter, dONGIAParameter, mALOAIDICHVUParameter);
        }
    
        public virtual int updateTypeRoom(string mALOAIPHONG, string tENLOAIPHONG, Nullable<byte> sONGUOI, string gHICHU)
        {
            var mALOAIPHONGParameter = mALOAIPHONG != null ?
                new ObjectParameter("MALOAIPHONG", mALOAIPHONG) :
                new ObjectParameter("MALOAIPHONG", typeof(string));
    
            var tENLOAIPHONGParameter = tENLOAIPHONG != null ?
                new ObjectParameter("TENLOAIPHONG", tENLOAIPHONG) :
                new ObjectParameter("TENLOAIPHONG", typeof(string));
    
            var sONGUOIParameter = sONGUOI.HasValue ?
                new ObjectParameter("SONGUOI", sONGUOI) :
                new ObjectParameter("SONGUOI", typeof(byte));
    
            var gHICHUParameter = gHICHU != null ?
                new ObjectParameter("GHICHU", gHICHU) :
                new ObjectParameter("GHICHU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateTypeRoom", mALOAIPHONGParameter, tENLOAIPHONGParameter, sONGUOIParameter, gHICHUParameter);
        }
    
        public virtual int updateTypeSer(string mALOAIDV, string tENLOAIDV)
        {
            var mALOAIDVParameter = mALOAIDV != null ?
                new ObjectParameter("MALOAIDV", mALOAIDV) :
                new ObjectParameter("MALOAIDV", typeof(string));
    
            var tENLOAIDVParameter = tENLOAIDV != null ?
                new ObjectParameter("TENLOAIDV", tENLOAIDV) :
                new ObjectParameter("TENLOAIDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateTypeSer", mALOAIDVParameter, tENLOAIDVParameter);
        }
    
        public virtual int addRoom(string mAPHONG, string tENPHONG, Nullable<byte> tINHTRANG, Nullable<int> dIENTICH, Nullable<double> gIATHUE, string mALOAI)
        {
            var mAPHONGParameter = mAPHONG != null ?
                new ObjectParameter("MAPHONG", mAPHONG) :
                new ObjectParameter("MAPHONG", typeof(string));
    
            var tENPHONGParameter = tENPHONG != null ?
                new ObjectParameter("TENPHONG", tENPHONG) :
                new ObjectParameter("TENPHONG", typeof(string));
    
            var tINHTRANGParameter = tINHTRANG.HasValue ?
                new ObjectParameter("TINHTRANG", tINHTRANG) :
                new ObjectParameter("TINHTRANG", typeof(byte));
    
            var dIENTICHParameter = dIENTICH.HasValue ?
                new ObjectParameter("DIENTICH", dIENTICH) :
                new ObjectParameter("DIENTICH", typeof(int));
    
            var gIATHUEParameter = gIATHUE.HasValue ?
                new ObjectParameter("GIATHUE", gIATHUE) :
                new ObjectParameter("GIATHUE", typeof(double));
    
            var mALOAIParameter = mALOAI != null ?
                new ObjectParameter("MALOAI", mALOAI) :
                new ObjectParameter("MALOAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addRoom", mAPHONGParameter, tENPHONGParameter, tINHTRANGParameter, dIENTICHParameter, gIATHUEParameter, mALOAIParameter);
        }
    
        public virtual int delRoom(string mAPHONG)
        {
            var mAPHONGParameter = mAPHONG != null ?
                new ObjectParameter("MAPHONG", mAPHONG) :
                new ObjectParameter("MAPHONG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delRoom", mAPHONGParameter);
        }
    
        public virtual ObjectResult<DSPhong_Result> DSPhong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSPhong_Result>("DSPhong");
        }
    
        public virtual int updateRoom(string mAPHONG, string tENPHONG, Nullable<byte> tINHTRANG, Nullable<int> dIENTICH, Nullable<double> gIATHUE, string mALOAI)
        {
            var mAPHONGParameter = mAPHONG != null ?
                new ObjectParameter("MAPHONG", mAPHONG) :
                new ObjectParameter("MAPHONG", typeof(string));
    
            var tENPHONGParameter = tENPHONG != null ?
                new ObjectParameter("TENPHONG", tENPHONG) :
                new ObjectParameter("TENPHONG", typeof(string));
    
            var tINHTRANGParameter = tINHTRANG.HasValue ?
                new ObjectParameter("TINHTRANG", tINHTRANG) :
                new ObjectParameter("TINHTRANG", typeof(byte));
    
            var dIENTICHParameter = dIENTICH.HasValue ?
                new ObjectParameter("DIENTICH", dIENTICH) :
                new ObjectParameter("DIENTICH", typeof(int));
    
            var gIATHUEParameter = gIATHUE.HasValue ?
                new ObjectParameter("GIATHUE", gIATHUE) :
                new ObjectParameter("GIATHUE", typeof(double));
    
            var mALOAIParameter = mALOAI != null ?
                new ObjectParameter("MALOAI", mALOAI) :
                new ObjectParameter("MALOAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateRoom", mAPHONGParameter, tENPHONGParameter, tINHTRANGParameter, dIENTICHParameter, gIATHUEParameter, mALOAIParameter);
        }
    
        public virtual ObjectResult<TKtypeRoom_Result> TKtypeRoom(string tENLOAIPHONG)
        {
            var tENLOAIPHONGParameter = tENLOAIPHONG != null ?
                new ObjectParameter("TENLOAIPHONG", tENLOAIPHONG) :
                new ObjectParameter("TENLOAIPHONG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TKtypeRoom_Result>("TKtypeRoom", tENLOAIPHONGParameter);
        }
    
        public virtual ObjectResult<TKPhong_Result> TKPhong(string tENPHONG)
        {
            var tENPHONGParameter = tENPHONG != null ?
                new ObjectParameter("TENPHONG", tENPHONG) :
                new ObjectParameter("TENPHONG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TKPhong_Result>("TKPhong", tENPHONGParameter);
        }
    
        public virtual ObjectResult<TKService_Result> TKService(string tENDV)
        {
            var tENDVParameter = tENDV != null ?
                new ObjectParameter("TENDV", tENDV) :
                new ObjectParameter("TENDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TKService_Result>("TKService", tENDVParameter);
        }
    
        public virtual ObjectResult<TKtypeService_Result> TKtypeService(string tENLOAIDV)
        {
            var tENLOAIDVParameter = tENLOAIDV != null ?
                new ObjectParameter("TENLOAIDV", tENLOAIDV) :
                new ObjectParameter("TENLOAIDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TKtypeService_Result>("TKtypeService", tENLOAIDVParameter);
        }
    }


    public virtual int updateCus(string mAKH, string tENKH, string cMND, string dIACHI, string sDT)
    {

        var mAKHParameter = mAKH != null ?
            new ObjectParameter("MAKH", mAKH) :
            new ObjectParameter("MAKH", typeof(string));


        var tENKHParameter = tENKH != null ?
            new ObjectParameter("TENKH", tENKH) :
            new ObjectParameter("TENKH", typeof(string));


        var cMNDParameter = cMND != null ?
            new ObjectParameter("CMND", cMND) :
            new ObjectParameter("CMND", typeof(string));


        var dIACHIParameter = dIACHI != null ?
            new ObjectParameter("DIACHI", dIACHI) :
            new ObjectParameter("DIACHI", typeof(string));


        var sDTParameter = sDT != null ?
            new ObjectParameter("SDT", sDT) :
            new ObjectParameter("SDT", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateCus", mAKHParameter, tENKHParameter, cMNDParameter, dIACHIParameter, sDTParameter);
    }


    public virtual ObjectResult<logIn_Result> logIn(string tentk, string matkhau)
    {

        var tentkParameter = tentk != null ?
            new ObjectParameter("tentk", tentk) :
            new ObjectParameter("tentk", typeof(string));


        var matkhauParameter = matkhau != null ?
            new ObjectParameter("matkhau", matkhau) :
            new ObjectParameter("matkhau", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<logIn_Result>("logIn", tentkParameter, matkhauParameter);
    }


    public virtual int delEmp(string mANV)
    {

        var mANVParameter = mANV != null ?
            new ObjectParameter("MANV", mANV) :
            new ObjectParameter("MANV", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delEmp", mANVParameter);
    }


    public virtual ObjectResult<getallEmp_Result> getallEmp()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getallEmp_Result>("getallEmp");
    }


    public virtual int updateAcc(string mANV, string tenTK, string matkhau, Nullable<bool> quyen)
    {

        var mANVParameter = mANV != null ?
            new ObjectParameter("MANV", mANV) :
            new ObjectParameter("MANV", typeof(string));


        var tenTKParameter = tenTK != null ?
            new ObjectParameter("tenTK", tenTK) :
            new ObjectParameter("tenTK", typeof(string));


        var matkhauParameter = matkhau != null ?
            new ObjectParameter("matkhau", matkhau) :
            new ObjectParameter("matkhau", typeof(string));


        var quyenParameter = quyen.HasValue ?
            new ObjectParameter("quyen", quyen) :
            new ObjectParameter("quyen", typeof(bool));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateAcc", mANVParameter, tenTKParameter, matkhauParameter, quyenParameter);
    }


    public virtual int updateEmp(string mANV, string hOTEN, Nullable<System.DateTime> nGAYSINH, string sDT)
    {

        var mANVParameter = mANV != null ?
            new ObjectParameter("MANV", mANV) :
            new ObjectParameter("MANV", typeof(string));


        var hOTENParameter = hOTEN != null ?
            new ObjectParameter("HOTEN", hOTEN) :
            new ObjectParameter("HOTEN", typeof(string));


        var nGAYSINHParameter = nGAYSINH.HasValue ?
            new ObjectParameter("NGAYSINH", nGAYSINH) :
            new ObjectParameter("NGAYSINH", typeof(System.DateTime));


        var sDTParameter = sDT != null ?
            new ObjectParameter("SDT", sDT) :
            new ObjectParameter("SDT", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateEmp", mANVParameter, hOTENParameter, nGAYSINHParameter, sDTParameter);
    }


    public virtual int addEmp(string mANV, string hOTEN, Nullable<System.DateTime> nGAYSINH, string sDT)
    {

        var mANVParameter = mANV != null ?
            new ObjectParameter("MANV", mANV) :
            new ObjectParameter("MANV", typeof(string));


        var hOTENParameter = hOTEN != null ?
            new ObjectParameter("HOTEN", hOTEN) :
            new ObjectParameter("HOTEN", typeof(string));


        var nGAYSINHParameter = nGAYSINH.HasValue ?
            new ObjectParameter("NGAYSINH", nGAYSINH) :
            new ObjectParameter("NGAYSINH", typeof(System.DateTime));


        var sDTParameter = sDT != null ?
            new ObjectParameter("SDT", sDT) :
            new ObjectParameter("SDT", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addEmp", mANVParameter, hOTENParameter, nGAYSINHParameter, sDTParameter);
    }


    public virtual ObjectResult<getAcc1_Result> getAcc1()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAcc1_Result>("getAcc1");
    }


    public virtual ObjectResult<string> getIdMPT()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getIdMPT");
    }


    public virtual ObjectResult<string> wellCome(string tenTk, string matKhau)
    {

        var tenTkParameter = tenTk != null ?
            new ObjectParameter("TenTk", tenTk) :
            new ObjectParameter("TenTk", typeof(string));


        var matKhauParameter = matKhau != null ?
            new ObjectParameter("MatKhau", matKhau) :
            new ObjectParameter("MatKhau", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("wellCome", tenTkParameter, matKhauParameter);
    }


    public virtual int changePass(string matkhauhientai, string idnv)
    {

        var matkhauhientaiParameter = matkhauhientai != null ?
            new ObjectParameter("matkhauhientai", matkhauhientai) :
            new ObjectParameter("matkhauhientai", typeof(string));


        var idnvParameter = idnv != null ?
            new ObjectParameter("idnv", idnv) :
            new ObjectParameter("idnv", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("changePass", matkhauhientaiParameter, idnvParameter);
    }


    public virtual ObjectResult<string> getIdNV(string tenTk, string matKhau)
    {

        var tenTkParameter = tenTk != null ?
            new ObjectParameter("TenTk", tenTk) :
            new ObjectParameter("TenTk", typeof(string));


        var matKhauParameter = matKhau != null ?
            new ObjectParameter("MatKhau", matKhau) :
            new ObjectParameter("MatKhau", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getIdNV", tenTkParameter, matKhauParameter);
    }


    public virtual ObjectResult<getCusFrPhieuThue_Result> getCusFrPhieuThue(string maphieuthue)
    {

        var maphieuthueParameter = maphieuthue != null ?
            new ObjectParameter("maphieuthue", maphieuthue) :
            new ObjectParameter("maphieuthue", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCusFrPhieuThue_Result>("getCusFrPhieuThue", maphieuthueParameter);
    }


    public virtual ObjectResult<tienphongDetail_Result> tienphongDetail(string mptp)
    {

        var mptpParameter = mptp != null ?
            new ObjectParameter("mptp", mptp) :
            new ObjectParameter("mptp", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tienphongDetail_Result>("tienphongDetail", mptpParameter);
    }


    public virtual ObjectResult<tienDvDetail_Result> tienDvDetail(string maptp)
    {

        var maptpParameter = maptp != null ?
            new ObjectParameter("maptp", maptp) :
            new ObjectParameter("maptp", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tienDvDetail_Result>("tienDvDetail", maptpParameter);
    }


    public virtual int creatBill(string maHD, Nullable<double> tienphong, Nullable<double> tiendv, Nullable<double> tongtien, Nullable<bool> hinhthuctt, Nullable<System.DateTime> ngaytt, string ghichu, string mptp)
    {

        var maHDParameter = maHD != null ?
            new ObjectParameter("maHD", maHD) :
            new ObjectParameter("maHD", typeof(string));


        var tienphongParameter = tienphong.HasValue ?
            new ObjectParameter("tienphong", tienphong) :
            new ObjectParameter("tienphong", typeof(double));


        var tiendvParameter = tiendv.HasValue ?
            new ObjectParameter("tiendv", tiendv) :
            new ObjectParameter("tiendv", typeof(double));


        var tongtienParameter = tongtien.HasValue ?
            new ObjectParameter("tongtien", tongtien) :
            new ObjectParameter("tongtien", typeof(double));


        var hinhthucttParameter = hinhthuctt.HasValue ?
            new ObjectParameter("hinhthuctt", hinhthuctt) :
            new ObjectParameter("hinhthuctt", typeof(bool));


        var ngayttParameter = ngaytt.HasValue ?
            new ObjectParameter("ngaytt", ngaytt) :
            new ObjectParameter("ngaytt", typeof(System.DateTime));


        var ghichuParameter = ghichu != null ?
            new ObjectParameter("ghichu", ghichu) :
            new ObjectParameter("ghichu", typeof(string));


        var mptpParameter = mptp != null ?
            new ObjectParameter("mptp", mptp) :
            new ObjectParameter("mptp", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("creatBill", maHDParameter, tienphongParameter, tiendvParameter, tongtienParameter, hinhthucttParameter, ngayttParameter, ghichuParameter, mptpParameter);
    }


    public virtual ObjectResult<string> getHTTT()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getHTTT");
    }


    public virtual int creatBill1(string maHD, Nullable<double> tienphong, Nullable<double> tiendv, Nullable<double> tongtien, Nullable<bool> hinhthuctt, Nullable<System.DateTime> ngaytt, string ghichu, string mptp)
    {

        var maHDParameter = maHD != null ?
            new ObjectParameter("maHD", maHD) :
            new ObjectParameter("maHD", typeof(string));


        var tienphongParameter = tienphong.HasValue ?
            new ObjectParameter("tienphong", tienphong) :
            new ObjectParameter("tienphong", typeof(double));


        var tiendvParameter = tiendv.HasValue ?
            new ObjectParameter("tiendv", tiendv) :
            new ObjectParameter("tiendv", typeof(double));


        var tongtienParameter = tongtien.HasValue ?
            new ObjectParameter("tongtien", tongtien) :
            new ObjectParameter("tongtien", typeof(double));


        var hinhthucttParameter = hinhthuctt.HasValue ?
            new ObjectParameter("hinhthuctt", hinhthuctt) :
            new ObjectParameter("hinhthuctt", typeof(bool));


        var ngayttParameter = ngaytt.HasValue ?
            new ObjectParameter("ngaytt", ngaytt) :
            new ObjectParameter("ngaytt", typeof(System.DateTime));


        var ghichuParameter = ghichu != null ?
            new ObjectParameter("ghichu", ghichu) :
            new ObjectParameter("ghichu", typeof(string));


        var mptpParameter = mptp != null ?
            new ObjectParameter("mptp", mptp) :
            new ObjectParameter("mptp", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("creatBill1", maHDParameter, tienphongParameter, tiendvParameter, tongtienParameter, hinhthucttParameter, ngayttParameter, ghichuParameter, mptpParameter);
    }


    public virtual ObjectResult<getDoanhThuTienDV_Result> getDoanhThuTienDV(Nullable<System.DateTime> ngayvaochon, Nullable<System.DateTime> ngayrachon)
    {

        var ngayvaochonParameter = ngayvaochon.HasValue ?
            new ObjectParameter("ngayvaochon", ngayvaochon) :
            new ObjectParameter("ngayvaochon", typeof(System.DateTime));


        var ngayrachonParameter = ngayrachon.HasValue ?
            new ObjectParameter("ngayrachon", ngayrachon) :
            new ObjectParameter("ngayrachon", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDoanhThuTienDV_Result>("getDoanhThuTienDV", ngayvaochonParameter, ngayrachonParameter);
    }


    public virtual ObjectResult<getDoanhThuTienPhong_Result> getDoanhThuTienPhong(Nullable<System.DateTime> ngayvaochon, Nullable<System.DateTime> ngayrachon)
    {

        var ngayvaochonParameter = ngayvaochon.HasValue ?
            new ObjectParameter("ngayvaochon", ngayvaochon) :
            new ObjectParameter("ngayvaochon", typeof(System.DateTime));


        var ngayrachonParameter = ngayrachon.HasValue ?
            new ObjectParameter("ngayrachon", ngayrachon) :
            new ObjectParameter("ngayrachon", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDoanhThuTienPhong_Result>("getDoanhThuTienPhong", ngayvaochonParameter, ngayrachonParameter);
    }

}
