//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_SoftWare2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class htEntities : DbContext
    {
        public htEntities()
            : base("name=htEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietPhieuThue> ChiTietPhieuThues { get; set; }
        public virtual DbSet<DichVu> DichVus { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiDichVu> LoaiDichVus { get; set; }
        public virtual DbSet<LoaiPhong> LoaiPhongs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuSuDungDichVu> PhieuSuDungDichVus { get; set; }
        public virtual DbSet<PhieuThuePhong> PhieuThuePhongs { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int addCus(string mAKH, string tENKH, string cMND, string dIACHI, string sDT)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            var tENKHParameter = tENKH != null ?
                new ObjectParameter("TENKH", tENKH) :
                new ObjectParameter("TENKH", typeof(string));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addCus", mAKHParameter, tENKHParameter, cMNDParameter, dIACHIParameter, sDTParameter);
        }
    
        public virtual int delCus(string mAKH)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delCus", mAKHParameter);
        }
    
        public virtual ObjectResult<getAccount_Result> getAccount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAccount_Result>("getAccount");
        }
    
        public virtual ObjectResult<getallCus_Result> getallCus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getallCus_Result>("getallCus");
        }
    
        public virtual int updateCus(string mAKH, string tENKH, string cMND, string dIACHI, string sDT)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            var tENKHParameter = tENKH != null ?
                new ObjectParameter("TENKH", tENKH) :
                new ObjectParameter("TENKH", typeof(string));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateCus", mAKHParameter, tENKHParameter, cMNDParameter, dIACHIParameter, sDTParameter);
        }
    
        public virtual ObjectResult<logIn_Result> logIn(string tentk, string matkhau)
        {
            var tentkParameter = tentk != null ?
                new ObjectParameter("tentk", tentk) :
                new ObjectParameter("tentk", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<logIn_Result>("logIn", tentkParameter, matkhauParameter);
        }
    
        public virtual int delEmp(string mANV)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delEmp", mANVParameter);
        }
    
        public virtual ObjectResult<getallEmp_Result> getallEmp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getallEmp_Result>("getallEmp");
        }
    
        public virtual int updateAcc(string mANV, string tenTK, string matkhau, Nullable<bool> quyen)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var tenTKParameter = tenTK != null ?
                new ObjectParameter("tenTK", tenTK) :
                new ObjectParameter("tenTK", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var quyenParameter = quyen.HasValue ?
                new ObjectParameter("quyen", quyen) :
                new ObjectParameter("quyen", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateAcc", mANVParameter, tenTKParameter, matkhauParameter, quyenParameter);
        }
    
        public virtual int updateEmp(string mANV, string hOTEN, Nullable<System.DateTime> nGAYSINH, string sDT)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var hOTENParameter = hOTEN != null ?
                new ObjectParameter("HOTEN", hOTEN) :
                new ObjectParameter("HOTEN", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateEmp", mANVParameter, hOTENParameter, nGAYSINHParameter, sDTParameter);
        }
    
        public virtual int addEmp(string mANV, string hOTEN, Nullable<System.DateTime> nGAYSINH, string sDT)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var hOTENParameter = hOTEN != null ?
                new ObjectParameter("HOTEN", hOTEN) :
                new ObjectParameter("HOTEN", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addEmp", mANVParameter, hOTENParameter, nGAYSINHParameter, sDTParameter);
        }
    
        public virtual int addSer(string mADV, string tENDV, Nullable<double> dONGIA, string mALOAIDICHVU)
        {
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            var tENDVParameter = tENDV != null ?
                new ObjectParameter("TENDV", tENDV) :
                new ObjectParameter("TENDV", typeof(string));
    
            var dONGIAParameter = dONGIA.HasValue ?
                new ObjectParameter("DONGIA", dONGIA) :
                new ObjectParameter("DONGIA", typeof(double));
    
            var mALOAIDICHVUParameter = mALOAIDICHVU != null ?
                new ObjectParameter("MALOAIDICHVU", mALOAIDICHVU) :
                new ObjectParameter("MALOAIDICHVU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addSer", mADVParameter, tENDVParameter, dONGIAParameter, mALOAIDICHVUParameter);
        }
    
        public virtual ObjectResult<DSKHTP_Result> DSKHTP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSKHTP_Result>("DSKHTP");
        }
    
        public virtual ObjectResult<DSNV_Result> DSNV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSNV_Result>("DSNV");
        }
    
        public virtual int HTTT(string hTTT)
        {
            var hTTTParameter = hTTT != null ?
                new ObjectParameter("HTTT", hTTT) :
                new ObjectParameter("HTTT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HTTT", hTTTParameter);
        }
    
        public virtual ObjectResult<TENNV_Result> TENNV(string tenNV)
        {
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TENNV_Result>("TENNV", tenNVParameter);
        }
    
        public virtual ObjectResult<TIMNV_Result> TIMNV(string tenKH)
        {
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TIMNV_Result>("TIMNV", tenKHParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> TKKH(string tenLoaiPhong)
        {
            var tenLoaiPhongParameter = tenLoaiPhong != null ?
                new ObjectParameter("TenLoaiPhong", tenLoaiPhong) :
                new ObjectParameter("TenLoaiPhong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TKKH", tenLoaiPhongParameter);
        }
    
        public virtual ObjectResult<TKKHTHEOPHONG_Result> TKKHTHEOPHONG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TKKHTHEOPHONG_Result>("TKKHTHEOPHONG");
        }
    
        public virtual ObjectResult<TKKHTHEOSOLANTHUE_Result> TKKHTHEOSOLANTHUE(Nullable<int> sOLANTHUE)
        {
            var sOLANTHUEParameter = sOLANTHUE.HasValue ?
                new ObjectParameter("SOLANTHUE", sOLANTHUE) :
                new ObjectParameter("SOLANTHUE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TKKHTHEOSOLANTHUE_Result>("TKKHTHEOSOLANTHUE", sOLANTHUEParameter);
        }
    
        public virtual ObjectResult<TKKHTHEOSOPHONGTHUE_Result> TKKHTHEOSOPHONGTHUE(Nullable<int> sOPHONGTHUE)
        {
            var sOPHONGTHUEParameter = sOPHONGTHUE.HasValue ?
                new ObjectParameter("SOPHONGTHUE", sOPHONGTHUE) :
                new ObjectParameter("SOPHONGTHUE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TKKHTHEOSOPHONGTHUE_Result>("TKKHTHEOSOPHONGTHUE", sOPHONGTHUEParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> TKKHTHEOTHANG(string tHANG)
        {
            var tHANGParameter = tHANG != null ?
                new ObjectParameter("THANG", tHANG) :
                new ObjectParameter("THANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TKKHTHEOTHANG", tHANGParameter);
        }
    
        public virtual ObjectResult<TTKH_Result> TTKH(string maKH)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TTKH_Result>("TTKH", maKHParameter);
        }
    
        public virtual ObjectResult<TTNV_Result> TTNV(string maNV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TTNV_Result>("TTNV", maNVParameter);
        }
    
        public virtual ObjectResult<DSDichVu_Result> DSDichVu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSDichVu_Result>("DSDichVu");
        }
    
        public virtual int updateSer(string mADV, string tENDV, Nullable<double> dONGIA, string mALOAIDICHVU)
        {
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            var tENDVParameter = tENDV != null ?
                new ObjectParameter("TENDV", tENDV) :
                new ObjectParameter("TENDV", typeof(string));
    
            var dONGIAParameter = dONGIA.HasValue ?
                new ObjectParameter("DONGIA", dONGIA) :
                new ObjectParameter("DONGIA", typeof(double));
    
            var mALOAIDICHVUParameter = mALOAIDICHVU != null ?
                new ObjectParameter("MALOAIDICHVU", mALOAIDICHVU) :
                new ObjectParameter("MALOAIDICHVU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateSer", mADVParameter, tENDVParameter, dONGIAParameter, mALOAIDICHVUParameter);
        }
    
        public virtual int delSer(string mADV)
        {
            var mADVParameter = mADV != null ?
                new ObjectParameter("MADV", mADV) :
                new ObjectParameter("MADV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delSer", mADVParameter);
        }
    
        public virtual int addTypeSer(string mALOAIDV, string tENLOAIDV)
        {
            var mALOAIDVParameter = mALOAIDV != null ?
                new ObjectParameter("MALOAIDV", mALOAIDV) :
                new ObjectParameter("MALOAIDV", typeof(string));
    
            var tENLOAIDVParameter = tENLOAIDV != null ?
                new ObjectParameter("TENLOAIDV", tENLOAIDV) :
                new ObjectParameter("TENLOAIDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addTypeSer", mALOAIDVParameter, tENLOAIDVParameter);
        }
    
        public virtual int delTypeSer(string mALOAIDV)
        {
            var mALOAIDVParameter = mALOAIDV != null ?
                new ObjectParameter("MALOAIDV", mALOAIDV) :
                new ObjectParameter("MALOAIDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delTypeSer", mALOAIDVParameter);
        }
    
        public virtual ObjectResult<DSLoaiDichVu_Result> DSLoaiDichVu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSLoaiDichVu_Result>("DSLoaiDichVu");
        }
    
        public virtual int updateTypeSer(string mALOAIDV, string tENLOAIDV)
        {
            var mALOAIDVParameter = mALOAIDV != null ?
                new ObjectParameter("MALOAIDV", mALOAIDV) :
                new ObjectParameter("MALOAIDV", typeof(string));
    
            var tENLOAIDVParameter = tENLOAIDV != null ?
                new ObjectParameter("TENLOAIDV", tENLOAIDV) :
                new ObjectParameter("TENLOAIDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateTypeSer", mALOAIDVParameter, tENLOAIDVParameter);
        }
    }
}
