
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hotel_SoftWare2
{

using System;
    using System.Collections.Generic;
    
public partial class DichVu
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DichVu()
    {

        this.PhieuSuDungDichVus = new HashSet<PhieuSuDungDichVu>();

    }


    public string MaDV { get; set; }

    public string TenDV { get; set; }

    public Nullable<double> DonGia { get; set; }

    public string MaLoaiDV { get; set; }



    public virtual LoaiDichVu LoaiDichVu { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PhieuSuDungDichVu> PhieuSuDungDichVus { get; set; }

}

}
