//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_SoftWare2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHoaDon { get; set; }
        public Nullable<double> TienPhong { get; set; }
        public Nullable<double> TienDV { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<bool> HinhThucThanhToan { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public string GhiChu { get; set; }
        public string MaPhieuThuePhong { get; set; }
    
        public virtual PhieuThuePhong PhieuThuePhong { get; set; }
    }
}
