
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hotel_SoftWare2
{

using System;
    using System.Collections.Generic;
    
public partial class PhieuSuDungDichVu
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PhieuSuDungDichVu()
    {

        this.PhieuThuePhongs = new HashSet<PhieuThuePhong>();

    }


    public string MaSD { get; set; }

    public Nullable<System.DateTime> NgaySD { get; set; }

    public Nullable<byte> SoLuong { get; set; }

    public Nullable<double> GiaTien { get; set; }

    public string MaDV { get; set; }



    public virtual DichVu DichVu { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PhieuThuePhong> PhieuThuePhongs { get; set; }

}

}
